CREATE TABLE `board` (
	`NO` INTEGER PRIMARY KEY AUTOINCREMENT,
	`TITLE` VARCHAR(100),
	`CONTENTS` VARCHAR(500),
	`REGDATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX `board_idx1`
ON board (regdate);

CREATE TABLE `file` (
	`uuid` VARCHAR(100) PRIMARY KEY,
	`fileName` VARCHAR(200) NOT NULL,
	`filePath` VARCHAR(100) NOT NULL,
	`boardNo`INTEGER NOT NULL,
	CONSTRAINT `file_fk1` FOREIGN KEY (`boardNo`) REFERENCES `board` (`NO`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX `file_fk1`
ON 'file' (boardNo);
