CREATE TABLE `board` (
	`NO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CONTENTS` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`REGDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`NO`),
	INDEX `board_idx1` (`REGDATE`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;

CREATE TABLE `file` (
	`uuid` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`fileName` VARCHAR(200) NOT NULL COLLATE 'utf8_bin',
	`filePath` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`boardNo` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`uuid`),
	INDEX `file_fk1` (`boardNo`),
	CONSTRAINT `file_fk1` FOREIGN KEY (`boardNo`) REFERENCES `board` (`NO`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;